
#// in aws what we do is production env
#spring.config.import=aws-secretsmanager:/prod/netflux/db/customer?prefix=db.
spring.datasource.url=jdbc:postgresql://netflux-db.cy94gkkyoz9h.us-east-1.rds.amazonaws.com:5432/customer
spring.datasource.username=customer_user
spring.datasource.password=customer_password_123
movie.service.url=http://movie-service:8080
server.port=8080
